-- artisan-db-oracle/schema.sql

-- 1. Users Table
CREATE TABLE Users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Artisans Table
CREATE TABLE Artisans (
    artisan_id NUMBER PRIMARY KEY,
    bio CLOB,
    craft_type VARCHAR2(100) NOT NULL,
    cover_image_path VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_artisan_user FOREIGN KEY (artisan_id) REFERENCES Users(id) ON DELETE CASCADE
);

-- 3. Bookings Table
CREATE TABLE Bookings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    artisan_id NUMBER NOT NULL,
    description CLOB,
    image_path VARCHAR2(255),
    status VARCHAR2(50) DEFAULT 'pending',
    scheduled_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_artisan FOREIGN KEY (artisan_id) REFERENCES Artisans(artisan_id) ON DELETE CASCADE
);
